### ISSUE TITLE
Add the ability to use `PVC` instead `HostPath` in API `statefulSet`

### ISSUE THREAD

**Issue by juhosyrjanen** [ProtoPie/helm-charts#5]
Hello again, 

We're taking Protopie into use at Metacore Games and really like the product. I'm in the works of deploying Protopie to our Kubernetes platform, but I am running into some issues with the Helm chart. I've already been making some PRs for you guys adding some small improvements to the Helm chart. However, this is a bit bigger one and since I have so many PRs open, I thought I rather open a discussion here. 

So,  the `enterprice-cloud-api` uses `HostPath` to specify `logs` , `download`, and `default` volumes. 

api-statefulset.yaml
```
...
      volumes:
        - name: logs
          hostPath:
            path: /home/ec2-user/logs
            type: DirectoryOrCreate
        - name: download
          hostPath:
            path: /home/ec2-user/download
            type: DirectoryOrCreate
        - name: default
          hostPath:
            path: /home/ec2-user/default
            type: DirectoryOrCreate
...
```

This causes issues with our setup, as we do not allow `ec2-user` directory modifications and would like to run AWS Bottlerocker EC2 nodes that do not allow this.  Instead, I suggest to use PVC for these volumes as well. To not break current functionality, one can add an `if` statement to the `statefulSet`:

api-statefulset.yaml
```
...
volumes:
        {{- if .Values.cloud.volumes.usePVC }}
        - name: logs
          persistentVolumeClaim:
            claimName: logs-enterprise-cloud-api
        - name: download
          persistentVolumeClaim:
            claimName: download-enterprise-cloud-api
        - name: default
          persistentVolumeClaim:
            claimName: default-enterprise-cloud-api
        {{- else }}
        - name: logs
          hostPath:
            path: /home/ec2-user/logs
            type: DirectoryOrCreate
        - name: download
          hostPath:
            path: /home/ec2-user/download
            type: DirectoryOrCreate
        - name: default
          hostPath:
            path: /home/ec2-user/default
            type: DirectoryOrCreate
        {{- end }}
...
```

In addition, add PVCs with a similar `if` statement (this assumes my `storageClassName` PR is approved):

pvc.yaml
```
{{- if .Values.cloud.volumes.usePVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ent-cloud-api
  name: logs-enterprise-cloud-api
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.cloud.volumes.logs | default "1Gi" }}
  {{- if .Values.cloud.volumes.storageClassName }}
  storageClassName: {{ .Values.cloud.volumes.storageClassName }}
  {{- end }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ent-cloud-api
  name: download-enterprise-cloud-api
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.cloud.volumes.download | default "1Gi" }}
  {{- if .Values.cloud.volumes.storageClassName }}
  storageClassName: {{ .Values.cloud.volumes.storageClassName }}
  {{- end }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ent-cloud-api
  name: default-enterprise-cloud-api
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.cloud.volumes.default | default "1Gi" }}
  {{- if .Values.cloud.volumes.storageClassName }}
  storageClassName: {{ .Values.cloud.volumes.storageClassName }}
  {{- end }}
{{- end }}

```

`values.yml` file could then be modified to support this:

values.yml
```
cloud:
  host: ""
  share:
    enabled: false
    host: ""
  api:
    replicas: 1
  web:
    replicas: 1
  volumes:
    # Default accessMode is ReadWriteMany
    accessMode: "ReadWriteOnce"
    usePVC: false
    upload: 50Gi
    logs: "5Gi"
    download: "5Gi"
    default: "5Gi"
```

Please consider when you have time :) We're happy to fork the chart for the time being to make this work for us.

**Comment by juhosyrjanen** [comment]
Hey again, I've been messing around a bit with this, here's a working api-statefulset.yaml:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enterprise-cloud-api
  labels:
    {{- include "protopie.labels" . | nindent 4 }}
spec:
  serviceName: ent-cloud-api-svc
  replicas: {{ .Values.cloud.api.replicas }}
  selector:
    matchLabels:
      app: ent-cloud-api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: ent-cloud-api
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- else if .Values.imageCredentials }}
      imagePullSecrets:
      - name: protopie-private-registry
      {{- end }}
      containers:
        - name: ent-cloud-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.cloud.api.repository }}:{{ .Values.image.cloud.api.tag }}"
          imagePullPolicy: {{ .Values.image.cloud.api.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.db.env.DB_HOST }}
            - name: DB_PORT
              value: !!str {{ .Values.db.env.DB_PORT | toString }}
            - name: POSTGRES_USER
              value: {{ .Values.db.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.env.POSTGRES_PASSWORD }}
            - name: DB_DATABASE
              value: {{ .Values.db.env.DB_DATABASE }}
            - name: DB_READ_USER
              value: {{ .Values.db.env.DB_READ_USER }}
            - name: DB_WRITE_USER
              value: {{ .Values.db.env.DB_WRITE_USER }}
            - name: DB_READ_PASSWORD
              value: {{ .Values.db.env.DB_READ_PASSWORD }}
            - name: DB_WRITE_PASSWORD
              value: {{ .Values.db.env.DB_WRITE_PASSWORD }}
            {{- with .Values.cloud.envs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3333
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: upload
              mountPath: /app/upload
            - name: download
              mountPath: /app/download
            - name: default
              mountPath: /app/default
            - name: config
              mountPath: /app/resources
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.cloud.volumes.usePVC }}
        - name: logs
          persistentVolumeClaim:
            claimName: logs-enterprise-cloud-api
        - name: download
          persistentVolumeClaim:
            claimName: download-enterprise-cloud-api
        - name: default
          persistentVolumeClaim:
            claimName: default-enterprise-cloud-api
        {{- else }}
        - name: logs
          hostPath:
            path: /home/ec2-user/logs
            type: DirectoryOrCreate
        - name: download
          hostPath:
            path: /home/ec2-user/download
            type: DirectoryOrCreate
        - name: default
          hostPath:
            path: /home/ec2-user/default
            type: DirectoryOrCreate
        {{- end }}
        - name: config
          projected:
            sources:
              - configMap:
                  name: config
              - configMap:
                  name: license
        - name: upload
          persistentVolumeClaim:
            claimName: upload-enterprise-cloud-api

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ent-cloud-api
  name: upload-enterprise-cloud-api
spec:
  accessModes:
  - {{ .Values.cloud.volumes.accessMode | default "ReadWriteMany" | quote }}
  resources:
    requests:
      storage: {{ .Values.cloud.volumes.upload }}
  {{- if .Values.cloud.volumes.storageClassName }}
  storageClassName: {{ .Values.cloud.volumes.storageClassName }}
  {{- end }}

---

{{- if .Values.cloud.volumes.usePVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ent-cloud-api
  name: logs-enterprise-cloud-api
spec:
  accessModes:
    - {{ .Values.cloud.volumes.accessMode | default "ReadWriteMany" | quote }}
  resources:
    requests:
      storage: {{ .Values.cloud.volumes.logs | default "1Gi" }}
  {{- if .Values.cloud.volumes.storageClassName }}
  storageClassName: {{ .Values.cloud.volumes.storageClassName }}
  {{- end }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ent-cloud-api
  name: download-enterprise-cloud-api
spec:
  accessModes:
    - {{ .Values.cloud.volumes.accessMode | default "ReadWriteMany" | quote }}
  resources:
    requests:
      storage: {{ .Values.cloud.volumes.download | default "1Gi" }}
  {{- if .Values.cloud.volumes.storageClassName }}
  storageClassName: {{ .Values.cloud.volumes.storageClassName }}
  {{- end }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ent-cloud-api
  name: default-enterprise-cloud-api
spec:
  accessModes:
    - {{ .Values.cloud.volumes.accessMode | default "ReadWriteMany" | quote }}
  resources:
    requests:
      storage: {{ .Values.cloud.volumes.default | default "1Gi" }}
  {{- if .Values.cloud.volumes.storageClassName }}
  storageClassName: {{ .Values.cloud.volumes.storageClassName }}
  {{- end }}
{{- end }}

```


values.yml here that enables the PVC: 

```
cloud:
  host: ""
  share:
    enabled: false
    host: ""
  api:
    replicas: 1
  web:
    replicas: 1
  volumes:
    # If left empty, the default storage class will be used
    storageClassName: ""
    # Default accessMode is ReadWriteMany
    accessMode: "ReadWriteOnce"
    usePVC: true
    upload: 50Gi
    logs: 5Gi
    download: 10Gi
    default: 10Gi

```
